spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1:3306}/${MYSQL_DATABASE:miniautorizador}?createDatabaseIfNotExist=true
    username: username
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
server:
  port: ${PORT:8080}
